enum Constants {
    UPDATE_TRANSLATING = 'UPDATE_TRANSLATING',
    UPDATE_LANGUAGE = 'UPDATE_LANGUAGE',
    UPDATE_FETCHING_FLOW = 'FETCHING_FLOW',
    UPDATE_DEFINITION = 'UPDATE_DEFINITION',
    UPDATE_NODE_DRAGGING = 'UPDATE_NODE_DRAGGING',
    UPDATE_FLOWS = 'UPDATE_FLOWS',
    UPDATE_DEPENDENCIES = 'UPDATE_DEPENDENCIES'
}

export default Constants;
